### ISSUE TITLE
ZTS incompatible calls

### ISSUE THREAD

**Issue by piotras** [midgardproject/midgard-php5#108]
As seen on travis tests, some calls do not set TSRMLS_CC argument. PHP on travis is compiled with threads enabled.

**Comment by piotras** [comment]
Master and Ratatoskr branches now build at travis. Considering fixed.

**Comment by flack** [comment]
Not sure if this is the same problem, but gjallarhorn is still refusing to build:

https://travis-ci.org/flack/openpsa/jobs/5471473/#L605

ratatoskr works fine now

**Comment by piotras** [comment]
Do you use master branch? 
https://github.com/midgardproject/midgard-php5/commit/9fd1e4e4f9da2a466666c059ebeb63599addae0f
I fixed that already, so either you use gjallarhorn branch or travis/github does some tricks.

**Comment by flack** [comment]
I'm not really sure, the Travis scripts were done by @bergie, and I have to admit I haven't really looked at them yet. But I would guess that the configuration named "gjallarhorn" indeed uses the gjallarhorn branch. We can of course switch this to master, but just out of curiosity: What is the status of the gjallarhorn branch? I was under the impression that it is the current stable and the successor to ratatoskr (in fact, I didn't even know that there is a separate master branch). But from what you write it sounds more like it is somehow deprecated. This wouldn't be a big problem for me, since I have only some test installations with it that I could switch to another branch, I'd just like to me sure before I start :-)

**Comment by piotras** [comment]
I created gjallarhorn branch and then realized that we should use master to avoid so many branches and changes within. All in all current work happens in master so gjallarhorn is just temporary snapshot and should be used only then, when we start new generation in a future. I'll check if I can update travis related scripts.

**Comment by piotras** [comment]
https://github.com/flack/openpsa/blob/master/.travis.yml
Change gjallarhorn to master and run test again.

**Comment by flack** [comment]
Alright, I switched, and now the tests run again. Will update my other installations accordingly
